//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEUA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convenio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Convenio()
        {
            this.Facultad = new HashSet<Facultad>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Fecha { get; set; }
        public string Documento { get; set; }
        public int Numero_Decreto { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha_expiracion { get; set; }
        public string Periocidad { get; set; }
        public int Contacto_Id { get; set; }
        public Nullable<int> Organizacion_Id { get; set; }
        public int Carrera_Id { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Contacto Contacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facultad> Facultad { get; set; }
        public virtual Organizacion Organizacion { get; set; }
    }
}
